#pragma once

// Generated by oparroy-dsl from design/node_pins.py — do not edit.
// Regenerate: python -m design.node_pins > firmware/node/pins.hpp
//
// oparroy ring-node pin map — CH32V003F4P6 (TSSOP-20). Function requests, pads bound late as
// refinement data (T9; DESIGN.md §5).
// 16 of 18 GPIO assigned; spare: PC1 (pin 11), PC7 (pin 17).

#include <cstdint>

namespace pins {

// GPIO port register-block base addresses (RM §1.2).
inline constexpr uint32_t gpio_a_base = 0x40010800;
inline constexpr uint32_t gpio_c_base = 0x40011000;
inline constexpr uint32_t gpio_d_base = 0x40011400;

// One pad as firmware sees it: the port register block, the bit
// inside it, and the package pin for schematic cross-reference.
struct Pad {
    uint32_t port_base;
    uint8_t bit;
    uint8_t package_pin;
};

// rx_a — ring A receive, OPA positive input; TIM2_CH1 capture is the internal route, no GPIO spent
// on the comparator output (§2).
inline constexpr Pad rx_a{.port_base = gpio_a_base, .bit = 2, .package_pin = 6};
inline constexpr uint8_t rx_a_opa_p = 0;
inline constexpr uint8_t rx_a_capture_dma = 5;
inline constexpr uint8_t rx_a_period_dma = 7;

// rx_b — ring B receive, OPA positive input; source select is firmware policy via OPA_PSEL (§3).
inline constexpr Pad rx_b{.port_base = gpio_d_base, .bit = 7, .package_pin = 4};
inline constexpr uint8_t rx_b_opa_p = 1;

// rx_threshold — VDD/2 slice threshold on an OPA negative input (§2).
inline constexpr Pad rx_threshold{.port_base = gpio_a_base, .bit = 1, .package_pin = 5};
inline constexpr uint8_t rx_threshold_opa_n = 0;

// comp_out — comparator-output tap for the §6 instrumented boundary node.
inline constexpr Pad comp_out{.port_base = gpio_d_base, .bit = 4, .package_pin = 1};

// tx_a — ring A transmit, TIM1 PWM + DMA compare streaming (§2).
inline constexpr Pad tx_a{.port_base = gpio_d_base, .bit = 2, .package_pin = 19};
inline constexpr uint8_t tx_a_tim1_ch = 1;
inline constexpr uint8_t tx_a_tx_dma = 2;

// tx_b — ring B transmit, second TIM1 channel, identical compare values (§3).
inline constexpr Pad tx_b{.port_base = gpio_c_base, .bit = 3, .package_pin = 13};
inline constexpr uint8_t tx_b_tim1_ch = 3;
inline constexpr uint8_t tx_b_tx_dma = 6;

// tx_kill — TIM1 brake, the hardware TX-kill for the watchdog / babbling-idiot story (§2).
inline constexpr Pad tx_kill{.port_base = gpio_c_base, .bit = 2, .package_pin = 12};

// keepalive — 20 kHz strobe holding the §4 charge-pump watchdog open.
inline constexpr Pad keepalive{.port_base = gpio_d_base, .bit = 3, .package_pin = 20};

// led_working — heartbeat LED; dark when firmware is hung or dead (§4.1).
inline constexpr Pad led_working{.port_base = gpio_d_base, .bit = 0, .package_pin = 8};

// led_segments — link-status LEDs at both segment connectors, one antiparallel pair behind a shared
// series R on a single pin (§4.1): pin high lights upstream, pin low downstream, Hi-Z dark, a kHz
// toggle lights both at half brightness.
inline constexpr Pad led_segments{.port_base = gpio_c_base, .bit = 0, .package_pin = 10};

// debug_tx — debug UART TX, collected by the supervisor (§6).
inline constexpr Pad debug_tx{.port_base = gpio_d_base, .bit = 5, .package_pin = 2};

// pot — potentiometer wiper, the demonstrator analog input (§6).
inline constexpr Pad pot{.port_base = gpio_d_base, .bit = 6, .package_pin = 3};
inline constexpr uint8_t pot_adc = 6;

// buzzer — buzzer PWM output (§5 I/O complement).
inline constexpr Pad buzzer{.port_base = gpio_c_base, .bit = 4, .package_pin = 14};
inline constexpr uint8_t buzzer_tim1_ch = 4;

// button_a — demo button input, FT pad (§5, §7 terminal rule).
inline constexpr Pad button_a{.port_base = gpio_c_base, .bit = 5, .package_pin = 15};

// button_b — demo button input, FT pad (§5, §7 terminal rule).
inline constexpr Pad button_b{.port_base = gpio_c_base, .bit = 6, .package_pin = 16};

// Reserved — counted in the GPIO budget, never firmware GPIO:
//   PD1 (pin 18): SWIO single-wire debug, no remap (quirks.md §Debug).

} // namespace pins
